[phases.setup]
nixPkgs = ["php84", "composer"]

[variables]
NIXPACKS_PHP_VERSION = "8.4"

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php -S 0.0.0.0:$PORT -t public"
